package view;


import controller.OrderController;
import javax.swing.JOptionPane;
import model.Orders;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class AddOrderForm extends javax.swing.JFrame {

    /**
     * Creates new form AddOrderForm
     */
    public AddOrderForm() {
        initComponents();
         idLable.setText(OrderController.generateId());
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        orderIdLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        sizeLable = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        OrderIdLabel = new javax.swing.JLabel();
        sizeText = new javax.swing.JTextField();
        qtyText = new javax.swing.JTextField();
        customerIdText = new javax.swing.JTextField();
        amountLabel1 = new javax.swing.JLabel();
        placeButton = new javax.swing.JButton();
        sizeLabel2 = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();
        viewAmountLabel = new javax.swing.JLabel();

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("jTextField1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Place Order");
        setResizable(false);

        backButton.setBackground(new java.awt.Color(255, 102, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        orderIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderIdLabel.setText("Order ID :");

        customerIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerIdLabel.setText("Customer ID :");

        sizeLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sizeLable.setText("Size :");

        qtyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyLabel.setText("QTY :");

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amountLabel.setText("Amount :");

        OrderIdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        sizeText.setEditable(false);
        sizeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sizeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTextActionPerformed(evt);
            }
        });
        sizeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sizeTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sizeTextKeyTyped(evt);
            }
        });

        qtyText.setEditable(false);
        qtyText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });
        qtyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTextKeyTyped(evt);
            }
        });

        customerIdText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextActionPerformed(evt);
            }
        });
        customerIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerIdTextKeyReleased(evt);
            }
        });

        amountLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        placeButton.setBackground(new java.awt.Color(55, 168, 161));
        placeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeButton.setForeground(new java.awt.Color(255, 255, 255));
        placeButton.setText("Place");
        placeButton.setPreferredSize(new java.awt.Dimension(85, 37));
        placeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeButtonActionPerformed(evt);
            }
        });

        sizeLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sizeLabel2.setText("(XS/S/M/L/XL/XXL)");

        idLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLable.setText("xxxxxxxxx");

        viewAmountLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OrderIdLabel)
                            .addComponent(amountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(sizeText)
                            .addComponent(qtyText)
                            .addComponent(idLable)
                            .addComponent(viewAmountLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(sizeLabel2)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(placeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderIdLabel)
                    .addComponent(idLable))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel1)
                    .addComponent(viewAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(placeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new HomeMain().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTextActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void customerIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextActionPerformed
         
				   
    }//GEN-LAST:event_customerIdTextActionPerformed

    private void placeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeButtonActionPerformed
        if (!(qtyText.getText().isEmpty())) {
            String orderId = idLable.getText();
            String customerId = customerIdText.getText();
            String size1 = sizeText.getText().toUpperCase();
            int qty1 = Integer.parseInt(qtyText.getText());
            double amount1 = Double.parseDouble(viewAmountLabel.getText());
            Orders newOrder = new Orders(orderId, customerId, size1, qty1, amount1, 0);
            boolean isAdded = OrderController.addOrder(newOrder);
            if (isAdded) {
                JOptionPane.showMessageDialog(null, "Order Placed..");
            }
            dispose();
            new HomeMain().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please Fill the Form..");
        }
    }//GEN-LAST:event_placeButtonActionPerformed

    private void sizeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTextActionPerformed
      
    }//GEN-LAST:event_sizeTextActionPerformed

    private void customerIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIdTextKeyReleased
        sizeText.setEditable(false);
        String input = customerIdText.getText();
        char firstChar = input.charAt(0);
        if (firstChar != '0' || input.length() > 10) {
            JOptionPane.showMessageDialog(null, "Invalid Input");
            customerIdText.setText("");
        }
        if (input.length() == 10) {
            sizeText.setEditable(true);
        }
    }//GEN-LAST:event_customerIdTextKeyReleased

    private void sizeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeTextKeyReleased
        String size = sizeText.getText().toUpperCase();
        if (!(size.equals("XS") || size.equals("S") || size.equals("M") || size.equals("L") || size.equals("XL") || size.equals("XXL"))) {
            JOptionPane.showMessageDialog(null, "error");
            sizeText.setText("");
        } else {
            qtyText.setEditable(true);
        }
    }//GEN-LAST:event_sizeTextKeyReleased

    private void qtyTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyReleased
        String size = sizeText.getText().toUpperCase();
        String qty = qtyText.getText();
        
        char firstChar = qtyText.getText().charAt(0);
        if (firstChar == 45 || firstChar == 48) {
            JOptionPane.showMessageDialog(this, "Pleaes enter positive value..!");
            qtyText.setText("");     
        } else {
           viewAmountLabel.setText(String.format("%.2f",OrderController.findAmount(qty,size))); 
        }
    }//GEN-LAST:event_qtyTextKeyReleased

    private void qtyTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyTyped
        char c = evt.getKeyChar();        
        if ((!Character.isDigit(c)) ) {            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Pleaes enter positive value..!");
            
        }
    }//GEN-LAST:event_qtyTextKeyTyped

    private void sizeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeTextKeyTyped
        
    }//GEN-LAST:event_sizeTextKeyTyped

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OrderIdLabel;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JButton placeButton;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyText;
    private javax.swing.JLabel sizeLabel2;
    private javax.swing.JLabel sizeLable;
    private javax.swing.JTextField sizeText;
    private javax.swing.JLabel viewAmountLabel;
    // End of variables declaration//GEN-END:variables
}
