package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        allCustomerButton = new javax.swing.JButton();
        viewCustomerButton = new javax.swing.JButton();
        bestInCustomerButton = new javax.swing.JButton();
        amountButton = new javax.swing.JButton();
        allOrderButton = new javax.swing.JButton();
        qtyButton = new javax.swing.JButton();
        ordersByAmountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Reports");
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);

        backButton.setBackground(new java.awt.Color(255, 102, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        allCustomerButton.setBackground(new java.awt.Color(0, 204, 0));
        allCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        allCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        allCustomerButton.setText("All Customers");
        allCustomerButton.setPreferredSize(new java.awt.Dimension(150, 35));
        allCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomerButtonActionPerformed(evt);
            }
        });

        viewCustomerButton.setBackground(new java.awt.Color(0, 204, 0));
        viewCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        viewCustomerButton.setText("View Customers");
        viewCustomerButton.setPreferredSize(new java.awt.Dimension(150, 35));
        viewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerButtonActionPerformed(evt);
            }
        });

        bestInCustomerButton.setBackground(new java.awt.Color(0, 204, 0));
        bestInCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bestInCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        bestInCustomerButton.setText("Best In Customers");
        bestInCustomerButton.setPreferredSize(new java.awt.Dimension(150, 35));
        bestInCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestInCustomerButtonActionPerformed(evt);
            }
        });

        amountButton.setBackground(new java.awt.Color(0, 0, 204));
        amountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amountButton.setForeground(new java.awt.Color(255, 255, 255));
        amountButton.setText("Categorized By Amount");
        amountButton.setPreferredSize(new java.awt.Dimension(175, 35));
        amountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountButtonActionPerformed(evt);
            }
        });

        allOrderButton.setBackground(new java.awt.Color(102, 102, 102));
        allOrderButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        allOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        allOrderButton.setText("All Orders");
        allOrderButton.setPreferredSize(new java.awt.Dimension(160, 35));
        allOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allOrderButtonActionPerformed(evt);
            }
        });

        qtyButton.setBackground(new java.awt.Color(0, 0, 204));
        qtyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtyButton.setForeground(new java.awt.Color(255, 255, 255));
        qtyButton.setText("Categorized By QTY");
        qtyButton.setPreferredSize(new java.awt.Dimension(175, 35));
        qtyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyButtonActionPerformed(evt);
            }
        });

        ordersByAmountButton.setBackground(new java.awt.Color(102, 102, 102));
        ordersByAmountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordersByAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        ordersByAmountButton.setText("Orders By Amount");
        ordersByAmountButton.setPreferredSize(new java.awt.Dimension(160, 35));
        ordersByAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersByAmountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bestInCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ordersByAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(viewCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bestInCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordersByAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new HomeMain().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void allCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomerButtonActionPerformed
        dispose();
        new AllCustomerReports().setVisible(true);
    }//GEN-LAST:event_allCustomerButtonActionPerformed

    private void viewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerButtonActionPerformed
        dispose();
        new ViewCustomers().setVisible(true);
    }//GEN-LAST:event_viewCustomerButtonActionPerformed

    private void bestInCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestInCustomerButtonActionPerformed
        dispose();
        new BestInCustomers().setVisible(true);
    }//GEN-LAST:event_bestInCustomerButtonActionPerformed

    private void allOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allOrderButtonActionPerformed
        dispose();
        new AllOrders().setVisible(true);
    }//GEN-LAST:event_allOrderButtonActionPerformed

    private void qtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyButtonActionPerformed
        dispose();
        new ItemsByQty().setVisible(true);
    }//GEN-LAST:event_qtyButtonActionPerformed

    private void amountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountButtonActionPerformed
        dispose();
        new ItemsByAmount().setVisible(true);
    }//GEN-LAST:event_amountButtonActionPerformed

    private void ordersByAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersByAmountButtonActionPerformed
        dispose();
        new OrdersByAmount().setVisible(true);
    }//GEN-LAST:event_ordersByAmountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allCustomerButton;
    private javax.swing.JButton allOrderButton;
    private javax.swing.JButton amountButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bestInCustomerButton;
    private javax.swing.JButton ordersByAmountButton;
    private javax.swing.JButton qtyButton;
    private javax.swing.JButton viewCustomerButton;
    // End of variables declaration//GEN-END:variables
}
